spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.208.129:3306/handsome?severTimezone=UTC
    username: root
    password: 111111

  lettuce:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 2
      max-wait: -1
      time-between-eviction-runs:

  mail:
    host: smtp.qq.com
    port: 465
    username: 3157153831@qq.com
    password: tvotknudkgnrdhda
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  data:
    redis:
      host: 192.168.208.129
      port: 6379
      database: 0
      timeout: 3000

server:
  port: 8081

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO  # 根日志级别（INFO/DEBUG，DEBUG 更详细）
    org.example.handsome: DEBUG  # 你的项目包路径，设置为 DEBUG 打印详细日志
    org.springframework.security: DEBUG  # 打印 Spring Security 认证过程日志
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # 控制台日志格式